package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-02-19T15:43:20.969+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://vbank.hfu.de/", name = "IVBank")
@XmlSeeAlso({ObjectFactory.class})
public interface IVBank {

    @WebMethod
    @RequestWrapper(localName = "getCreditRate", targetNamespace = "http://vbank.hfu.de/", className = "soap.GetCreditRate")
    @ResponseWrapper(localName = "getCreditRateResponse", targetNamespace = "http://vbank.hfu.de/", className = "soap.GetCreditRateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Double getCreditRate(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
