package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-02-19T15:43:20.986+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "VBankService", 
                  wsdlLocation = "http://192.168.56.101:8080/VBankService/services/VBankPort?wsdl",
                  targetNamespace = "http://vbank.hfu.de/") 
public class VBankService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://vbank.hfu.de/", "VBankService");
    public final static QName VBankPort = new QName("http://vbank.hfu.de/", "VBankPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.56.101:8080/VBankService/services/VBankPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VBankService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.56.101:8080/VBankService/services/VBankPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VBankService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VBankService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VBankService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VBankService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VBankService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VBankService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IVBank
     */
    @WebEndpoint(name = "VBankPort")
    public IVBank getVBankPort() {
        return super.getPort(VBankPort, IVBank.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVBank
     */
    @WebEndpoint(name = "VBankPort")
    public IVBank getVBankPort(WebServiceFeature... features) {
        return super.getPort(VBankPort, IVBank.class, features);
    }

}
